# Generated by Django 3.0.8 on 2020-07-31 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sport', models.CharField(max_length=200)),
                ('Bovada_Link', models.CharField(max_length=200)),
                ('OnexBet_Link', models.CharField(max_length=200)),
                ('Team_OnexBet', models.CharField(max_length=200)),
                ('Team_Bovada', models.CharField(max_length=200)),
                ('Bet_Bovada', models.CharField(max_length=200)),
                ('Bet_OnexBet', models.CharField(max_length=200)),
                ('Remine_Time', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Profit_Percent', models.FloatField()),
                ('Odd_OnexBet', models.FloatField()),
                ('Odd_Bovada', models.FloatField()),
                ('OnexBet_Limit', models.FloatField()),
                ('Bovada_Limit', models.FloatField()),
                ('OnexBet_Win', models.BooleanField()),
                ('OpenBet', models.BooleanField()),
                ('Money_Bet_on_OnexBet', models.FloatField()),
                ('Money_Bet_on_Bovada', models.FloatField()),
                ('Final_Profit', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
